[package]
name = "shared_state"
version = "0.1.0"
authors = ["Mephisto"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["sync"] }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.21.3"
solana-sdk = "2.1.7"

[lib]
path = "src/lib.rs"